  METHOD if_oo_adt_classrun~main.
    DATA lt_error TYPE TABLE OF ydbs_t_gar_error.
    lt_error = VALUE #( ( code = '0101' message = 'Mükerrer BatchID.' )
                        ( code = '0102' message = 'ProcessingFlag hatalı.' )
                        ( code = '0103' message = 'PackageCount sıfır olamaz.' )
                        ( code = '0104' message = 'Kurum inaktif.' )
                        ( code = '0105' message = 'MainOperationCode hatalı.' )
                        ( code = '0199' message = 'Diğer Hata' )

                        ( code = '0201' message = 'Mükerrer paket.' )
                        ( code = '0202' message = 'Geçersiz BatchID.' )
                        ( code = '0204' message = 'PackageID geçersiz.' )
                        ( code = '0205' message = 'PackageID sıralama hatası.' )
                        ( code = '0206' message = 'PackageItemCount hatalı.' )
                        ( code = '0207' message = 'Paket içinde mükerrer kayıt. LogoUniqueID tekrar edilmiş.' )
                        ( code = '0208' message = 'Kurum bulunamadı veya inaktif.' )
                        ( code = '0299' message = 'Diğer Hata' )

                        ( code = '0301' message = 'Mükerrer BatchTrailer.' )
                        ( code = '0302' message = 'Beklenmeyen BatchTrailer.' )
                        ( code = '0304' message = 'BatchItemCount hatalı.' )
                        ( code = '0306' message = 'PackageCount hatalı.' )
                        ( code = '0399' message = 'Diğer hata.' )

                        ( code = '0401' message = 'Data tipi/formatı hatalı.' )
                        ( code = '0402' message = 'Zorunlu saha eksik.' )
                        ( code = '0403' message = 'Transfer tipi için hatalı bilgi' )
                        ( code = '0404' message = 'Borçlu hesap tanımlı değil.' )
                        ( code = '0405' message = 'Borçlu hesap ilgili işlem için kullanılamaz.' )
                        ( code = '0406' message = 'Alacak banka hatalı.' )
                        ( code = '0407' message = 'Alacak şube hatalı' )
                        ( code = '0408' message = 'Alacak hesap hatalı' )
                        ( code = '0409' message = 'Tutar sıfır olamaz.' )
                        ( code = '0410' message = 'TRL için tutar kuruşlu olamaz.' )
                        ( code = '0412' message = 'Borçlu/Alacaklı/Tutar döviz kodları uyumsuz.' )
                        ( code = '0413' message = 'EFT ise Döviz kodu TRL olmalı.' )
                        ( code = '0414' message = 'Vade tarihi geçmiş tarih olamaz.' )
                        ( code = '0415' message = 'EFT için vade tarihi tatil günü olamaz.' )
                        ( code = '0416' message = 'Kurum bulunamadı/inaktif.' )
                        ( code = '0417' message = 'Borçlu Hesap Kapalı' )
                        ( code = '0418' message = 'Alacak Hesap Kapalı' )
                        ( code = '0419' message = 'VKN formatı hatalı.' )
                        ( code = '0420' message = 'VKN bilgisi hatalı' )
                        ( code = '0421' message = 'IBAN diğer bankalara ait geçerli bir IBAN olmalıdır.' )
                        ( code = '0422' message = 'Online YP havale işlemlerinde kullanılacak borçlu hesabın döviz kodu YTL olmalıdır.' )
                        ( code = '0423' message = 'Online YP havale işlemlerinde ödemenin döviz kodu YTL olamaz.' )
                        ( code = '0424' message = 'Alacaklı YP hesabın döviz kodu ödeme döviz kodundan farklı olamaz.' )
                        ( code = '0425' message = 'Alacaklı YP ve alacaklı YTL hesapların müşterileri farklı olamaz.' )
                        ( code = '0426' message = 'PaymentType I olan işlemler için vade tarihi olmamalıdır.' )
                        ( code = '0427' message = 'Tarih günün tarihinden küçük olamaz.' )
                        ( code = '0428' message = 'Daha önce bu TrfUniqueID ile işlem yapılmamış.' )
                        ( code = '0429' message = 'IBAN Garanti Bankası’na ait geçerli bir IBAN olmalıdır.' )
                        ( code = '0430' message = 'TC Kimlik no formatı hatalı.' )
                        ( code = '0431' message = 'TC Kimlik no bilgisi hatalı.' )
                        ( code = '0432' message = 'IBAN hatalı' )
                        ( code = '0433' message = 'Ödeme tipi hatalı' )
                        ( code = '0434' message = 'Kur hatası' )
                        ( code = '0499' message = 'Diğer Hata' )

                        ( code = '0501' message = 'Bakiye Yetersiz' )
                        ( code = '0502' message = 'Ödeme Geri Alındı' )
                        ( code = '0504' message = 'Alacak Hesap Kapalı' )
                        ( code = '0505' message = 'Alacak Hesap Yok/Bulunamadı' )
                        ( code = '0507' message = 'Borçlu Hesap Kapalı' )
                        ( code = '0508' message = 'Borçlu Hesap Yok/Bulunamadı' )
                        ( code = '0510' message = 'Kurum Aktif Değil/Bulunamadı' )
                        ( code = '0599' message = 'Diğer Hata' )

                        ( code = '0801' message = 'Hesap kurumun MARS’ına bağlı olmalıdır.' )
                        ( code = '0802' message = 'Sadece vadesiz hesaplar için bakiye sorgulama yapılabilir' )
                        ( code = '0803' message = 'Şube kodu hatalı' )
                        ( code = '0804' message = 'Hesap hatalı' )
                        ( code = '0805' message = 'IBAN hatalı' )
                        ( code = '0806' message = 'TC Kimlik no formatı hatalı.' )
                        ( code = '0807' message = 'TC Kimlik no bilgisi hatalı.' )
                        ( code = '0808' message = 'VKN formatı hatalı.' )
                        ( code = '0809' message = 'VKN bilgisi hatalı' )

                        ( code = '9101' message = 'Hatalı sertifika no' )
                        ( code = '9102' message = 'Bu sertifika no ile ilgili işlem yapılamaz.' )
                        ( code = '9103' message = 'Sertifika şifre hatası.' )  ).
    MODIFY ydbs_t_gar_error FROM TABLE @lt_error.
    COMMIT WORK AND WAIT.
  ENDMETHOD.